spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liweiyuan/spring_cloud/
          search-paths: spring-config/config-repo
          username: 535767595@qq.com
          password: ****************
server:
  port: 1201